apiVersion: v1
data:
  .dockercfg: ew0KICAgICJjYzIxYWNyZmZkY2VkMDAxLmF6dXJlY3IuaW8iOiB7DQogICAgICAidXNlcm5hbWUiOiAiMzUyN2NiMTUtYjZmZi00NjMwLWFkYmUtZDY5MmM4OWFjZDZhIiwNCiAgICAgICJwYXNzd29yZCI6ICJNMmI4cmlCbStXckFzemtJVmVOckJOR1VyQzhJQzdoR2RDcHAyMldsL3hNPSIsDQogICAgICAiZW1haWwiOiAibWFjaWVqLm1hY2llamV3c2tpLmZpbmFzdHJhQGNyZWF0b3IuZnVzaW9uZmFicmljLmNsb3VkIiwNCiAgICAgICJhdXRoIjogIk16VXlOMk5pTVRVdFlqWm1aaTAwTmpNd0xXRmtZbVV0WkRZNU1tTTRPV0ZqWkRaaE9rMHlZamh5YVVKdEsxZHlRWE42YTBsV1pVNXlRazVIVlhKRE9FbEROMmhIWkVOd2NESXlWMnd2ZUUwOSINCiAgICB9DQp9
kind: Secret
metadata:
  name: cc21acrffdced001
  namespace: chassis-ns
type: kubernetes.io/dockercfg
