apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{applicationName}}-svc
  name: {{applicationName}}-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: {{applicationName}}-dpl
